#include <catch2/catch.hpp>
#include <iostream>

#include "../src/random.hpp"

TEST_CASE("UniformIntervalRNG") {
    SECTION("Generates numbers in the correct interval") {
        const auto gen = UniformIntervalRNG(-0.5f, 2.0f);
        std::cout << "Numbers generated by UniformIntervalRNG(-0.5f, 2.0f) : ";
        for (int i = 0; i < 20; ++i) {
            const float generatedNb = gen.generate();
            if (i % 5 == 0) {
                std::cout << '\n';
            }
            std::cout << generatedNb << "    ";
            REQUIRE((-0.5f <= generatedNb && generatedNb <= 2.0f));
        }
        std::cout << '\n' << '\n';
    }
}